### ISSUE TITLE
Freezes the game if you attempt to use the barter scanner on resolutions above 16:9

### ISSUE THREAD

**Issue by 7orbs** [wanjizheng/iBarter_WPF#2]
I have an ultrawide monitor (21:9), and if I attempt to use the barter scanner it completely freezes my game and shortly after crashes it. 

A sort of fix is to run the game in windowed mode at a 16:9 resolution however when I do this I keep getting "Check OCR range!" (not 100% sure if it's an actual error or not, but it is in red text) errors and the outputs are extremely inaccurate.

Can give more information if needed.

**Comment by wanjizheng** [comment]
Okay, I haven't tried resolutions above 16:9. Checking the OCR range means it doesn't scan the correct part of the screen. Will fix this in the future release.
